---
title: "ENVS 193DS Final"
author: "Sofie Flom"
date: "8 June 2025"
format:
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
  warning: false # use this to make sure warnings don't show up
---
[Repo link](https://github.com/sofie-f7/ENVS-193DS_spring-2025_final)

```{r packages-and-data, message=FALSE}

```

# Problem 1. 

## a. 

In part 1, they used a Pearson's r test. In part 2, they used an analysis of variance (one-way ANOVA) test. 

## b. 

One additional piece of information that should be included is the significance level that was used to compare the p-value. This would add useful additional context because it provides more transparency to the test that was done and tells how strict the test was.
Another test that should be included is Tukey's HSD. This would be useful because it would explain which sources are actually statistically different in mean nitrogen load from each other when you compare them. The ANOVA test result says that at least one group is significantly different, but not which one(s). 

## c. 

We rejected the null hypothesis that there is no correlation between distance from headwater (km) and annual total nitrogen load (kg year-1) (Pearson's r = **correlation coefficient**, p = 0.03, $\alpha$ = **significance level**).

We rejected the null hypothesis that there is no difference in average nitrogen load (kg year-1) between sources (n = sample sizes) (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) (one-way ANOVA, F(**among groups df, within groups df**) = **F-statistic**, p = 0.02, $\alpha$ = **significance level**). We found a ___ effect ($\eta^2$ = **effect size**) of nitrogen source on nitrogen load. On average, **source type** tended to have smaller/larger nitrogen loads than **source type** (**Tukey's HSD**).
